name: Build TawfiqWRT Cubie A5E

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils qemu-utils rsync sudo subversion swig texinfo u-boot-tools upx-ucl unzip vim wget xmlto xz-utils zlib1g-dev libz-dev
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Clone Kwrt Source
        run: |
          git clone --depth 1 https://github.com/kiddin9/Kwrt.git openwrt

      - name: Load Custom Configuration
        run: |
          cd openwrt
          # অলউইনার (sunxi) টার্গেট প্রোফাইল জেনারেট করা
          echo "CONFIG_TARGET_sunxi=y" > .config
          echo "CONFIG_TARGET_sunxi_cortexa7=y" >> .config
          echo "CONFIG_TARGET_DEVICE_sunxi_cortexa7_DEVICE_cubietech_cubieboard2=y" >> .config
          make defconfig

      - name: Compile Firmware
        run: |
          cd openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 V=s

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TawfiqWRT-CubieA5E-Image
          path: openwrt/bin/targets/
