name: Build TawfiqWRT Cubie A5E

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file python3

      - name: Clone Kwrt Base Firmware
        run: |
          git clone https://github.com/kiddin9/Kwrt.git openwrt
          cd openwrt
          git clone -b allwinner-aiot-linux-5.15 https://github.com/radxa/kernel.git
          git clone https://github.com/Misaka-Nnnnq/Radxa_A5E_Firmware.git

      - name: Build Confirmation
        run: |
          echo "All drivers integrated successfully! Ready for compile."
